src/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
]

src/gallery/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    url(r'^$', views.gallery_list, name='list'),
    url(r'^(?P<pk>[0-9]+)/$', views.gallery_detail, name='detail'),
    url(r'^create/$', views.gallery_create, name='create'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.gallery_update, name='edit'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.gallery_delete, name='delete'),

]

src/lisbon/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from . import views
from .sitemap import sitemaps

urlpatterns = [

    url(r'^$', views.home, name='home'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^', include('accounts.urls', namespace='accounts')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^users/', include('profiles.urls', namespace='profiles')),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^tours/', include('tours.urls', namespace='tour')),
    url(r'^reviews/', include('review.urls', namespace='review')),
    url(r'^gallery/', include('gallery.urls', namespace='gallery')),
    url(r'^contacts/', include('contacts.urls', namespace='contact')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^rent-car/', include('rent_car.urls', namespace='rent_car')),
    url(r'^rent-hotel/', include('rent_hotel.urls', namespace='rent_hotel')),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact-us/$', views.contact_us, name='contact_us'),
    url(r'^book-form/$', views.book_form, name='book_form'),
    url(r'^login-or-register/$', views.login_or_register, name='login_or_register'),
    url(r'^offer/', include('offer.urls', namespace='offer')),
    url(r'^category/', include('category.urls', namespace='category')),
    url(r'^related-links/', include('related_links.urls', namespace='related_links')),
    url(r'^email-me/', views.email_me, name='email_me'),


]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/news/urls.py
from django.conf.urls import url
from . import views

urlpatterns = (

    url(r'^$', views.news_list, name='list'),
    url(r'^create/$', views.news_create, name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.news_detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.news_update, name='edit'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.news_delete, name='delete'),
    # url(r'^(?P<slug>[\w-]+)/$', views.news_category, name='cat'),

)

src/offer/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.offer_list, name='list'),
    url(r'^create/$', views.offer_create, name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.offer_detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.offer_update, name='edit'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.offer_delete, name='delete'),

]

src/tours/urls.py
from django.conf.urls import url
from . import views

urlpatterns = (

    url(r'^$', views.tour_list, name='list'),
    url(r'^create/$', views.tour_create, name='create'),
    url(r'^success/$', views.tour_success, name='success'),
    url(r'^fail/$', views.tour_fail, name='fail'),
    url(r'^(?P<pk>[0-9]+)/$', views.tour_detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.tour_update, name='edit'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.tour_delete, name='delete'),
    url(r'^(?P<slug>[\w-]+)/$', views.tour_category, name='cat'),

)

src/contacts/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.translation import ugettext_lazy as _
from django.contrib import messages
from helpers.models import Helpers
from tours.models import Category
from .models import Contact, ContactHelpers
from .forms import ContactForm


def get_lang(request):
    lang = request.LANGUAGE_CODE
    return lang


def get_company():
    return Helpers.objects.get(id=1).company_name


def contact_list(request):
    lang = get_lang(request)
    queryset_list = Contact.objects.all()
    breadcrumbs = [
        {'url': '/', 'name': _('Home')},
        {'url': '#', 'name': _('Contacts'), 'active': True}
    ]
    query = request.GET.get('q')
    if query:
        queryset_list = queryset_list.filter(
            Q(first_name__icontains=query) |
            Q(last_name__icontains=query)
        ).distinct()
    paginator = Paginator(queryset_list, ContactHelpers.objects.get(id=1).pagination)
    page_request_var = 'page'
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)

    footer = {
        'pt': Helpers.objects.get(id=1).about_footer_PT,
        'en': Helpers.objects.get(id=1).about_footer_EN,
        'de': Helpers.objects.get(id=1).about_footer_DE
    }
    context = {
        'footer': {
            'about': footer[lang],
            'icon': Helpers.objects.get(id=1).footer_icon
        },
        'categories_list': Category.objects.all(),
        'company': get_company(),
        'title': _('Contacts'),
        'breadcrumbs': breadcrumbs,
        'object_list': queryset,
        'page_request_var': page_request_var,
    }

    return render(request, 'partials/contact.html', context)


def contact_detail(request, pk=None):
    lang = get_lang(request)
    contact = Contact.objects.get(pk=pk)
    breadcrumbs = [
        {'url': '/', 'name': _('Home')},
        {'url': '/contacts', 'name': _('Contacts')},
        {'url': '#', 'name': contact.first_name + ' ' + contact.last_name, 'active': True}
    ]
    footer = {
        'pt': Helpers.objects.get(id=1).about_footer_PT,
        'en': Helpers.objects.get(id=1).about_footer_EN,
        'de': Helpers.objects.get(id=1).about_footer_DE
    }
    context = {
        'footer': {
            'about': footer[lang],
            'icon': Helpers.objects.get(id=1).footer_icon
        },
        'categories_list': Category.objects.all(),
        'company': get_company(),
        'title': contact.first_name + ' ' + contact.last_name,
        'breadcrumbs': breadcrumbs,
        'object': contact,
    }

    return render(request, 'templates/_contact_details.html', context)


def contact_create(request):
    lang = get_lang(request)
    footer = {
        'pt': Helpers.objects.get(id=1).about_footer_PT,
        'en': Helpers.objects.get(id=1).about_footer_EN,
        'de': Helpers.objects.get(id=1).about_footer_DE
    }
    if not request.user.is_staff or not request.user.is_superuser:
        return redirect('accounts:signup')
    else:
        form = ContactForm(request.POST or None, request.FILES or None)
        breadcrumbs = [
            {'url': '/', 'name': _('Home')},
            {'url': '/contacts', 'name': _('Contacts')},
            {'url': '#', 'name': _('Create Contact'), 'active': True}
        ]
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            messages.success(request, _('Contact Created'))
            return redirect('contact:list')

        context = {
            'footer': {
                'about': footer[lang],
                'icon': Helpers.objects.get(id=1).footer_icon
            },
            'categories_list': Category.objects.all(),
            'company': get_company(),
            'title': _('Create Contact'),
            'breadcrumbs': breadcrumbs,
            'value': _('Add'),
            'form': form
        }

        return render(request, 'templates/_form.html', context)


def contact_update(request, pk=None):
    lang = get_lang(request)
    footer = {
        'pt': Helpers.objects.get(id=1).about_footer_PT,
        'en': Helpers.objects.get(id=1).about_footer_EN,
        'de': Helpers.objects.get(id=1).about_footer_DE
    }
    if not request.user.is_staff or not request.user.is_superuser:
        return redirect('accounts:signup')
    else:
        contact = get_object_or_404(Contact, pk=pk)
        breadcrumbs = [
            {'url': '/', 'name': _('Home')},
            {'url': '/contacts', 'name': _('Contacts')},
            {'url': '#', 'name': contact.first_name + ' ' + contact.last_name, 'active': True}
        ]
        form = ContactForm(request.POST or None, request.FILES or None, instance=contact)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.save()
            messages.success(request, _('Contact saved'))
            return redirect('contact:list')

        context = {
            'footer': {
                'about': footer[lang],
                'icon': Helpers.objects.get(id=1).footer_icon
            },
            'categories_list': Category.objects.all(),
            'company': get_company(),
            'title': _('Contact Edit'),
            'breadcrumbs': breadcrumbs,
            'instance': contact,
            'form': form,
            'value': _('Add'),
        }
        return render(request, 'templates/_form.html', context)


def contact_delete(request, pk=None):
    if not request.user.is_staff or not request.user.is_superuser:
        return redirect('accounts:signup')
    instance = get_object_or_404(Contact, pk=pk)
    instance.delete()
    messages.success(request, _('Contact deleted'))
    return redirect('contact:list')

src/gallery/views.py
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.translation import ugettext_lazy as _
from helpers.models import Helpers
from tours.models import Category
from .models import Gallery
from .forms import GalleryForm


def get_lang(request):
    lang = request.LANGUAGE_CODE
    return lang


def get_company():
    return Helpers.objects.get(id=1).company_name


def gallery_list(request):
    footer = {
        'pt': Helpers.objects.get(id=1).about_footer_PT,
        'en': Helpers.objects.get(id=1).about_footer_EN,
        'de': Helpers.objects.get(id=1).about_footer_DE
    }
    lang = get_lang(request)
    queryset_list = Gallery.objects.all()
    breadcrumbs = [
        {'url': '/', 'name': _('Home')},
        {'url': '#', 'name': _('Gallery'), 'active': True}
    ]
    query = request.GET.get('q')
    if query:
        if 'pt' in lang:
            queryset_list = queryset_list.filter(
                Q(title_PT__icontains=query) |
                Q(description_PT__icontains=query)
                # Q(category__category__icontains=query)
            ).distinct()
        else:
            if 'en' in lang:
                queryset_list = queryset_list.filter(
                    Q(title_EN__icontains=query) |
                    Q(description_EN__icontains=query)
                    # Q(category__category__icontains=query)
                ).distinct()
            else:
                if 'de' in lang:
                    queryset_list = queryset_list.filter(
                        Q(title_DE__icontains=query) |
                        Q(description_DE__icontains=query)
                        # Q(category__category__icontains=query)
                    ).distinct()
    paginator = Paginator(queryset_list, 6)
    page_request_var = 'page'
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)

    context = {
        'footer': {
            'about': footer[lang],
            'icon': Helpers.objects.get(id=1).footer_icon
        },
        'categories_list': Category.objects.all(),
        'company': get_company(),
        'title': _('Gallery'),
        'breadcrumbs': breadcrumbs,
        'object_list': queryset,
        'page_request_var': page_request_var,
    }

    return render(request, 'partials/gallery.html', context)


def gallery_detail(request, pk=None):
    gallery = Gallery.objects.get(pk=pk)
    lang = get_lang(request)
    footer = {
        'pt': Helpers.objects.get(id=1).about_footer_PT,
        'en': Helpers.objects.get(id=1).about_footer_EN,
        'de': Helpers.objects.get(id=1).about_footer_DE
    }
    gallery_title = {
        'pt': gallery.title_PT,
        'en': gallery.title_EN,
        'de': gallery.title_DE
    }
    gallery_description = {
        'pt': gallery.description_PT,
        'en': gallery.description_EN,
        'de': gallery.description_DE
    }
    breadcrumbs = [
        {'url': '/', 'name': _('Home')},
        {'url': '/gallery', 'name': _('Gallery')},
        {'url': '#', 'name': gallery_title[lang], 'active': True}
    ]
    gallery_current = {
        'title': gallery_title[lang],
        'description': gallery_description[lang],
        'id': gallery.id,
        'video': gallery.video,
        'img': gallery.img,
        'img1': gallery.img_1,
        'img2': gallery.img_2,
        'img3': gallery.img_3,
    }
    context = {
        'footer': {
            'about': footer[lang],
            'icon': Helpers.objects.get(id=1).footer_icon
        },
        'categories_list': Category.objects.all(),
        'company': get_company(),
        'breadcrumbs': breadcrumbs,
        'title': gallery_title[lang],
        'object': gallery_current,
    }

    return render(request, 'templates/_gallery_details.html', context)


def gallery_update(request, pk=None):
    footer = {
        'pt': Helpers.objects.get(id=1).about_footer_PT,
        'en': Helpers.objects.get(id=1).about_footer_EN,
        'de': Helpers.objects.get(id=1).about_footer_DE
    }
    lang = get_lang(request)
    if not request.user.is_staff or not request.user.is_superuser:
        return redirect('accounts:signup')
    else:
        gallery = get_object_or_404(Gallery, pk=pk)
        lang = get_lang(request)
        gallery_title = {
            'pt': gallery.title_PT,
            'en': gallery.title_EN,
            'de': gallery.title_DE
        }
        breadcrumbs = [
            {'url': '/', 'name': _('Home')},
            {'url': '/gallery', 'name': _('Gallery')},
            {'url': '#', 'name': gallery_title[lang], 'active': True}
        ]
        form = GalleryForm(request.POST or None, request.FILES or None, instance=gallery)
        if form.is_valid():
            gallery = form.save(commit=False)
            gallery.save()
            messages.success(request, _('Gallery edited'))
            return redirect('gallery:list')

        context = {
            'footer': {
                'about': footer[lang],
                'icon': Helpers.objects.get(id=1).footer_icon
            },
            'categories_list': Category.objects.all(),
            'company': get_company(),
            'title': _('Gallery edit'),
            'breadcrumbs': breadcrumbs,
            'instance': gallery,
            'form': form,
            'value': _('Add'),
        }
        return render(request, 'templates/_form.html', context)


def gallery_create(request):
    lang = get_lang(request)
    footer = {
        'pt': Helpers.objects.get(id=1).about_footer_PT,
        'en': Helpers.objects.get(id=1).about_footer_EN,
        'de': Helpers.objects.get(id=1).about_footer_DE
    }
    if not request.user.is_staff or not request.user.is_superuser:
        return redirect('accounts:signup')
    else:
        form = GalleryForm(request.POST or None, request.FILES or None)
        breadcrumbs = [
            {'url': '/', 'name': _('Home')},
            {'url': '/gallery', 'name': _('Gallery')},
            {'url': '#', 'name': _('Create Gallery'), 'active': True}
        ]
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            messages.success(request, _('Gallery created'))
            return redirect('gallery:list')

        context = {
            'footer': {
                'about': footer[lang],
                'icon': Helpers.objects.get(id=1).footer_icon
            },
            'categories_list': Category.objects.all(),
            'company': get_company(),
            'title': _('Create Gallery'),
            'breadcrumbs': breadcrumbs,
            'value': _('Add'),
            'form': form
        }

        return render(request, 'templates/_form.html', context)


def gallery_delete(request, pk=None):
    if not request.user.is_staff or not request.user.is_superuser:
        return redirect('accounts:signup')
    instance = get_object_or_404(Gallery, pk=pk)
    instance.delete()
    messages.success(request, _('Gallery deleted'))
    return redirect('gallery:list')

src/templates/partials/about.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
    {% include 'templates/_breadcrumbs.html' %}
    <section>
        <div class="container">
            <h1 class="display-4">{{ title }}</h1>
            {% if 'pt' in request.LANGUAGE_CODE %}
                {% for object in about_list %}
                    {% for paragraph in object.paragraph.all %}
                        <p>{{ paragraph.text_PT }}</p>
                    {% endfor %}
                {% endfor %}
            {% endif %}
            {% if 'en' in request.LANGUAGE_CODE %}
                {% for object in about_list %}
                    {% for paragraph in object.paragraph.all %}
                        <p>{{ paragraph.text_EN }}</p>
                    {% endfor %}
                {% endfor %}
            {% endif %}
            {% if 'de' in request.LANGUAGE_CODE %}
                {% for object in about_list %}
                    {% for paragraph in object.paragraph.all %}
                        <p>{{ paragraph.text_DE }}</p>
                    {% endfor %}
                {% endfor %}
            {% endif %}
        </div>
    </section>
{% endblock %}

src/templates/partials/contact.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{{ title }}{% endblock title %}
{% block beadcrumbs %}
    {% include 'templates/_breadcrumbs.html' %}
{% endblock %}
{% block content %}
    <section>
    <div class="container contact">
        <h1 class="display-4">{{ title }}</h1>
        <div class="card-columns">
            {% for object in object_list %}
                {% include 'templates/_contact_card.html' %}
            {% endfor %}
        </div>
        {% if user.is_staff or user.is_superuser %}
            <a class="btn btn-warning" href="{% url 'contact:create' %}"><i class="fa fa-plus"></i> {% trans 'Create Contact' %}</a>
        {% endif %}
        {% include 'templates/_pagination.html' %}
    </div>
    </section>
{% endblock %}

src/templates/partials/gallery.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
    {% include 'templates/_breadcrumbs.html' %}
    <section>
        <div class="container">
            <h1 class="display-4">{{ title }}</h1>
            <div class="card-columns">
                {% for object in object_list %}
                    {% include 'templates/_gallery_card.html' %}
                {% endfor %}
            </div>
            {% if user.is_staff or user.is_superuser %}
                <a class="btn btn-warning" href="{% url 'gallery:create' %}"><i class="fa fa-plus"></i> {% trans 'Create Gallery' %}</a>
            {% endif %}
            {% include 'templates/_pagination.html' %}
        </div>
    </section>
{% endblock %}

src/templates/partials/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% load thumbnail %}
{% load crispy_forms_tags %}
{% block title %}{% trans 'Home' %}{% endblock %}
{% block keywords %}{% endblock keywords %}
{% block description %}{% endblock description %}
{% block content %}
    {% include 'templates/_breadcrumbs.html' %}
    <article>
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                <li data-target="#carousel-example-generic" data-slide-to="3"></li>
                <li data-target="#carousel-example-generic" data-slide-to="4"></li>
            </ol>
            <div style="min-height: 600px; max-height: 600px" class="carousel-inner" role="listbox">
                <div class="carousel-item active">
                    <img style="width: 100%;object-fit: cover; min-height: 600px" src="{% thumbnail img1 1920x1080 crop="smart" %}">
                    <h1 class="main-header display-3 type">{{ header }}</h1>
                    <button class="btn btn-lg btn-gold btn-contact" data-toggle="modal" data-target="#contactUs">{% trans 'Contact us' %}</button>
                </div>
                <div class="carousel-item">
                    <img style="width: 100%;object-fit: cover; min-height: 600px" src="{% thumbnail img2 1920x1080 crop="smart" %}">
                    <h1 class="main-header display-3 type">{{ header }}</h1>
                    <button class="btn btn-lg btn-gold btn-contact" data-toggle="modal" data-target="#contactUs">{% trans 'Contact us' %}</button>
                </div>
                <div class="carousel-item">
                    <img style="width: 100%;object-fit: cover; min-height: 600px" src="{% thumbnail img3 1920x1080 crop="smart" %}">
                    <h1 class="main-header display-3 type">{{ header }}</h1>
                    <button class="btn btn-lg btn-gold btn-contact" data-toggle="modal" data-target="#contactUs">{% trans 'Contact us' %}</button>
                </div>
                <div class="carousel-item">
                    <img style="width: 100%;object-fit: cover; min-height: 600px" src="{% thumbnail img4 1920x1080 crop="smart" %}">
                    <h1 class="main-header display-3 type">{{ header }}</h1>
                    <button class="btn btn-lg btn-gold btn-contact" data-toggle="modal" data-target="#contactUs">{% trans 'Contact us' %}</button>
                </div>
                <div class="carousel-item">
                    <img style="width: 100%;object-fit: cover; min-height: 600px" src="{% thumbnail img5 1920x1080 crop="smart" %}">
                    <h1 class="main-header display-3 type">{{ header }}</h1>
                    <button class="btn btn-lg btn-gold btn-contact" data-toggle="modal" data-target="#contactUs">{% trans 'Contact us' %}</button>
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="icon-prev" aria-hidden="true"></span>
                <span class="sr-only">{% trans 'Previous' %}</span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="icon-next" aria-hidden="true"></span>
                <span class="sr-only">{% trans 'Next' %}</span>
            </a>
        </div>
    </article>
    <audio autoplay loop controls preload="true" class="player">
        <source src="media/{{ audio }}" type="audio/mpeg">
    </audio>
    <article class="tours">
        <div class="container">
            <h3 class="display-3 text-md-center">{{ section.tour_header }}</h3>
            <p style="text-align: center"><a href="{% url 'tour:list' %}">
                <em>{% trans 'full tour list' %}</em>
            </a></p>
            <div class="card-columns">
                {% if 'pt' in request.LANGUAGE_CODE %}
                    {% for object in tour_list %}
                        {% include 'templates/_tour_card_pt.html' %}
                    {% endfor %}
                {% endif %}
                {% if 'en' in request.LANGUAGE_CODE %}
                    {% for object in tour_list %}
                        {% include 'templates/_tour_card_gb.html' %}
                    {% endfor %}
                {% endif %}
                {% if 'de' in request.LANGUAGE_CODE %}
                    {% for object in tour_list %}
                        {% include 'templates/_tour_card_de.html' %}
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </article>
    <article class="offer">
        <div class="container marketing">
            <h3 class="display-3 text-md-center">{{ section.offer_header }}</h3>
            <p style="text-align: center"><a href="{% url 'offer:list' %}"><em>{% trans 'full offer list' %}</em></a></p>
            <div class="card-columns">
                {% for object in offer_list%}
                    {% include 'templates/_offer_card.html' %}
                {% endfor %}
            </div>
            {% if user.is_staff or user.is_superuser %}
                <a class="btn btn-warning" href="{% url 'offer:create' %}"><i class="fa fa-plus"></i> {% trans  'Create Offer' %}</a>
            {% endif %}
        </div>
    </article>
    {% include 'templates/modal/_contact_us.html' %}
{% endblock content %}

src/templates/partials/login_or_register.html
{% extends 'base.html' %}
{% block beadcrumbs %}
    {% include 'templates/_breadcrumbs.html' %}
{% endblock %}
{% block content %}
    <section>
    <div class="container">
        <h3 class="display-4">Please LOGIN or REGISTER to leave your reviews or comments. Thank you!</h3>
        <a class="btn btn-lg btn-success" href="{% url 'accounts:login' %}">Login</a>
        <a class="btn btn-lg btn-success" href="{% url 'accounts:signup' %}">Register</a>
    </div>
    </section>
{% endblock %}

src/templates/partials/review_filter.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
    {% include 'templates/_breadcrumbs.html' %}
    <section>
        <div class="container">
        <h1 class="display-4">{{ title }}</h1>
            {% for object in object_list %}
                {% if object.confirmed %}
                <blockquote class="blockquote">
                    <p class="m-b-0">{{ object.review|truncatechars:200 }}</p>
                    <p class="m-b-0"><span class="text-muted">left by: </span>{{ object.user.name }}</p>
                    <div class="blockquote-footer">add on: <cite title="Source Title">{{ object.timestamp }}</cite></div>
                    <a href="{% url 'review:list' %}{{ object.id }}/">{% trans 'View details' %}</a>
                </blockquote>
                {% endif %}
            {% endfor %}
            {% if not request.user.is_authenticated %}
                <a class="btn btn-warning" href="{% url 'review:create' %}"><i class="fa fa-plus"></i> {% trans 'Add Review' %}</a>
            {% else %}
                <a class="btn btn-warning" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap"><i class="fa fa-plus"></i> {% trans 'Add Review' %}</a>
            {% endif %}
            {% if user.is_staff or user.is_superuser %}
                <a class="btn btn-warning" href="/admin/review/review/"> {% trans 'To reviews list' %}</a>
            {% endif %}
            {% if request.user.is_authenticated %}
                <div style="z-index: 9999" class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <h4 class="modal-title" id="exampleModalLabel">{% trans 'Add Review' %}</h4>
                            </div>
                            <div class="modal-body">
                                {% include 'templates/_modal_form.html' %}
                            </div>
                        </div>
                    </div>
                </div>
            {% else %}
            {% endif %}
            {% include 'templates/_pagination.html' %}
        </div>
    </section>
{% endblock %}