src/lisbon/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from . import views
from .sitemap import sitemaps

urlpatterns = [

    url(r'^$', views.home, name='home'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^', include('accounts.urls', namespace='accounts')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^users/', include('profiles.urls', namespace='profiles')),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^tours/', include('tours.urls', namespace='tour')),
    url(r'^reviews/', include('review.urls', namespace='review')),
    url(r'^gallery/', include('gallery.urls', namespace='gallery')),
    url(r'^contacts/', include('contacts.urls', namespace='contact')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^rent-car/', include('rent_car.urls', namespace='rent_car')),
    url(r'^rent-hotel/', include('rent_hotel.urls', namespace='rent_hotel')),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact-us/$', views.contact_us, name='contact_us'),
    url(r'^book-form/$', views.book_form, name='book_form'),
    url(r'^login-or-register/$', views.login_or_register, name='login_or_register'),
    url(r'^offer/', include('offer.urls', namespace='offer')),
    url(r'^category/', include('category.urls', namespace='category')),
    url(r'^related-links/', include('related_links.urls', namespace='related_links')),
    url(r'^email-me/', views.email_me, name='email_me'),


]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/news/urls.py
from django.conf.urls import url
from . import views

urlpatterns = (

    url(r'^$', views.news_list, name='list'),
    url(r'^create/$', views.news_create, name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.news_detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.news_update, name='edit'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.news_delete, name='delete'),
    # url(r'^(?P<slug>[\w-]+)/$', views.news_category, name='cat'),

)

src/templates/templates/nav/_follow_us.html
{% load i18n %}
<h4 class="text-md-center text-sm-center text-xs-center">{% trans 'Contact Us' %}</h4>
<ol class="list-unstyled">
    <li class="text-md-center text-sm-center text-xs-center">
        <a href="#">{% trans 'Follow on ' %} Twitter <i class="fa fa-twitter"></i></a>
    </li>
    <li class="text-md-center text-sm-center text-xs-center">
        <a href="#">{% trans 'Follow on ' %} Facebook <i class="fa fa-facebook"></i></a>
    </li>
    <li class="text-md-center text-sm-center text-xs-center">
        <a href="#">{% trans 'Follow on ' %} Google + <i class="fa fa-google-plus"></i></a>
    </li>
    <li class="text-md-center text-sm-center text-xs-center">
        <a href="#">{% trans 'Follow on ' %} Instagram <i class="fa fa-instagram"></i></a>
    </li>
    <li class="text-md-center text-sm-center text-xs-center">
        <a href="{% url 'email_me' %}" >{% trans 'Email me' %} <i class="fa fa-mail-forward"></i></a>
    </li>
</ol>

src/templates/templates/nav/_nav_test.html
{% load i18n %}
<div class="navbar-collapse collapse inverse" id="navbar-header">
{#    <div class="container">#}
{#        <div class="row">#}
{#            <div class="col-md-6">#}
{#                <h4 class="text-md-center text-sm-center text-xs-center">{% trans 'Site Map' %}</h4>#}
                <ol style="margin: 0" class="list-unstyled">
                    <li style="padding: 20px" class="hidden-md-up text-md-center text-sm-center text-xs-center"><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
                    <li style="padding: 20px" class="hidden-md-up text-md-center text-sm-center text-xs-center"><a href="{% url 'tour:list' %}" >{% trans 'Tours & Excursions' %}</a></li>
                    <li style="padding: 20px" class="hidden-md-up text-md-center text-sm-center text-xs-center"><a href="{% url 'review:list' %}">{% trans 'Reviews' %}</a></li>
                    <li style="padding: 20px" class="hidden-md-up text-md-center text-sm-center text-xs-center"><a href="{% url 'gallery:list' %}">{% trans 'Gallery' %}</a></li>
                    <li style="padding: 20px" class="hidden-md-up text-md-center text-sm-center text-xs-center"><a href="{% url 'rent_car:list' %}">{% trans 'Car Rent in Lisbon' %}</a></li>
                    <li style="padding: 20px" class="hidden-md-up text-md-center text-sm-center text-xs-center"><a href="{% url 'rent_hotel:list' %}">{% trans 'Hotels in Lisbon' %}</a></li>
                    <li style="padding: 20px" class="hidden-md-up text-md-center text-sm-center text-xs-center"><a href="{% url 'about' %}">{% trans 'About Us' %}</a></li>
                    <li style="padding: 20px" class="hidden-md-up text-md-center text-sm-center text-xs-center"><a href="{% url 'contact:list' %}">{% trans 'Contacts' %}</a></li>
                    <li style="padding: 20px" class="hidden-md-up text-md-center text-sm-center text-xs-center"><a href="{% url 'news:list' %}">{% trans 'News' %}</a></li>
                    <li style="padding: 20px" class="hidden-md-up text-md-center text-sm-center text-xs-center"><a href="{% url 'related_links:list' %}">{% trans 'Related Links' %}</a></li>
                    {% if user.is_staff or user.is_superuser %}
                        <li style="padding: 20px" class="hidden-md-up text-md-center text-sm-center text-xs-center"><a href="/admin/">{% trans 'Admin Panel' %}</a></li>
                    {% endif %}
                    <li style="padding: 20px" class="text-md-center text-sm-center text-xs-center">
                        <form class="" method='GET' action=''>
            <input class="form-control" type='text' name='q' placeholder='{% trans 'Search' %}' value='{{ request.GET.q }}'/>
            <input class="btn btn-success-outline" type='submit' value='{% trans 'Search' %}' />
        </form>
                    </li>
                </ol>

{#            </div>#}
{#            <div class="col-md-6">#}
{#                {% include 'templates/nav/_follow_us.html' %}#}
{#            </div>#}
{#        </div>#}
    </div>
</div>
<div class="navbar navbar-static-top navbar-dark bg-inverse">
    <div class="container-fluid">
        <ol class="nav navbar-nav">
            <li class="nav-item hidden-lg-up">
                <button class="navbar-toggler" type="button" data-toggle='collapse' data-target="#navbar-header">
                    &#9776;
                </button>
            </li>
            <li class="nav-item hidden-sm-down">
                <a class="nav-link" href="{% url 'home' %}">{% trans 'Home' %}</a>
            </li>
            <li class="nav-item hidden-md-down">
                <div class="btn-group">
                <a style="cursor: pointer;color: gold;"  class=" hidden-sm-down nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% trans 'Tours & Excursions' %}</a>
                <div class="dropdown-menu">
                    {% if categories_list %}
                        {% for category in categories_list %}
                            <a href="/tours/{{ category.url }}" class="dropdown-item">{{ category.category }}</a>
                        {% endfor %}
                    {% endif %}
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'tour:list' %}">{% trans 'All Tours' %}</a>
                </div>
                </div>
            </li>
            <li class="nav-item hidden-sm-down">
                <div class="btn-group">
                    <a style="cursor: pointer;color: gold;"  class=" hidden-sm-down nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% trans 'Offers' %}</a>
                    <div class="dropdown-menu">
                        <a href="{% url 'rent_car:list' %}" class="dropdown-item">{% trans 'Car Rent in Lisbon' %}</a>
                        <a href="{% url 'rent_hotel:list' %}" class="dropdown-item">{% trans 'Hotels in Lisbon' %}</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'offer:list' %}">{% trans 'Full Offer list' %}</a>
                    </div>
                </div>
            </li>
            <li class="nav-item hidden-sm-down">
                <a class="nav-link" href="{% url 'about' %}">{% trans 'About Us' %}</a>
            </li>
            <li class="nav-item hidden-sm-down">
                <a class="nav-link" href="{% url 'contact:list' %}">{% trans 'Contacts' %}</a>
            </li>
            <li class="nav-item hidden-sm-down">
                <a class="nav-link" href="{% url 'news:list' %}">{% trans 'News' %}</a>
            </li>
            <li class="nav-item hidden-sm-down">
                <div class="btn-group">
                    <a style="cursor: pointer;color: gold;"  class=" hidden-sm-down nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% trans 'More' %}</a>
                    <div class="dropdown-menu">
                        <a href="{% url 'gallery:list' %}" class="dropdown-item">{% trans 'Gallery' %}</a>
                        <a href="{% url 'related_links:list' %}" class="dropdown-item">{% trans 'Related Links' %}</a>
                        <div class="dropdown-divider"></div>
                        <a href="{% url 'review:list' %}" class="dropdown-item">{% trans 'Reviews' %}</a>
                    </div>
                </div>
            </li>
            <li class="nav-item">
                {% include 'templates/_user.html' %}
            </li>
        </ol>
        <form class="form-inline pull-xs-right hidden-md-down" method='GET' action=''>
            <input class="form-control" type='text' name='q' placeholder='{% trans 'Search' %}' value='{{ request.GET.q }}'/>
            <input class="btn btn-success-outline" type='submit' value='{% trans 'Search' %}' />
        </form>
    </div>
</div>