src/lisbon/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from . import views
from .sitemap import sitemaps

urlpatterns = [

    url(r'^$', views.home, name='home'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^', include('accounts.urls', namespace='accounts')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^users/', include('profiles.urls', namespace='profiles')),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^tours/', include('tours.urls', namespace='tour')),
    url(r'^reviews/', include('review.urls', namespace='review')),
    url(r'^gallery/', include('gallery.urls', namespace='gallery')),
    url(r'^contacts/', include('contacts.urls', namespace='contact')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^rent-car/', include('rent_car.urls', namespace='rent_car')),
    url(r'^rent-hotel/', include('rent_hotel.urls', namespace='rent_hotel')),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact-us/$', views.contact_us, name='contact_us'),
    url(r'^book-form/$', views.book_form, name='book_form'),
    url(r'^login-or-register/$', views.login_or_register, name='login_or_register'),
    url(r'^offer/', include('offer.urls', namespace='offer')),
    url(r'^category/', include('category.urls', namespace='category')),
    url(r'^related-links/', include('related_links.urls', namespace='related_links')),
    url(r'^email-me/', views.email_me, name='email_me'),


]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/news/urls.py
from django.conf.urls import url
from . import views

urlpatterns = (

    url(r'^$', views.news_list, name='list'),
    url(r'^create/$', views.news_create, name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.news_detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.news_update, name='edit'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.news_delete, name='delete'),
    # url(r'^(?P<slug>[\w-]+)/$', views.news_category, name='cat'),

)

src/rent_hotel/urls.py
from django.conf.urls import url
from . import views

urlpatterns = (

    url(r'^$', views.rent_hotel_list, name='list'),
    # url(r'^create/$', views.rent_car_create, name='create'),
    # url(r'^(?P<pk>[0-9]+)/$', views.rent_car_detail, name='detail'),
    # url(r'^(?P<pk>[0-9]+)/edit/$', views.rent_car_update, name='edit'),
    # url(r'^(?P<pk>[0-9]+)/delete/$', views.rent_car_delete, name='delete'),
    # # url(r'^(?P<slug>[\w-]+)/$', views.rent_car_category, name='cat'),

)

src/rent_hotel/models.py
from django.db import models
from easy_thumbnails.fields import *
from autoslug.fields import *
from django.utils.translation import ugettext as _


class HotelCategory(models.Model):
    category = models.CharField(max_length=100, blank=True, null=False)
    url = AutoSlugField(populate_from='category', unique=True, max_length=255)

    def __str__(self):
        return self.category

    def __unicode__(self):
        return self.category


class Hotel(models.Model):
    title_PT = models.CharField(_('Title PT'), max_length=100, blank=True, null=False)
    title_EN = models.CharField(_('Title EN'), max_length=100, blank=True, null=False)
    title_DE = models.CharField(_('Title DE'), max_length=100, blank=True, null=False)
    description_PT = models.TextField(_('Hotel description PT'), max_length=1000, blank=True, null=False)
    description_EN = models.TextField(_('Hotel description EN'), max_length=1000, blank=True, null=False)
    description_DE = models.TextField(_('Hotel description DE'), max_length=1000, blank=True, null=False)
    address = models.TextField(_('Hotel address'), max_length=1000, blank=True, null=False)
    category = models.ForeignKey(HotelCategory, default=1, blank=True, null=True)
    price = models.CharField(_('Hotel price per day'), max_length=100, blank=True, null=False)
    trip_advisor_PT = models.TextField(_('Input script for widget from TripAdvisor PT'), max_length=2000, blank=True,
                                       null=False)
    trip_advisor_EN = models.TextField(_('Input script for widget from TripAdvisor EN'), max_length=2000, blank=True,
                                       null=False)
    trip_advisor_DE = models.TextField(_('Input script for widget from TripAdvisor DE'), max_length=2000, blank=True,
                                       null=False)
    # tour = models.ForeignKey(Tour, default=1, blank=True, null=True)
    # link = models.URLField(max_length=100, blank=True, null=False)
    img = ThumbnailerImageField(_('Hotel thumbnail'), null=True, blank=True)
    keywords_SEO = models.TextField(_('Hotel keywords for SEO'), max_length=1000, blank=True, null=False)
    description_SEO = models.TextField(_('Hotel description for SEO'), max_length=1000, blank=True, null=False)

    class Meta:
        # ordering = ['position', '-created_on']
        verbose_name_plural = _('Hotel')

    def get_absolute_url(self):
        return '/rent-hotel/%i/' % self.id

    def __str__(self):
        return self.title_EN

    def __unicode__(self):
        return self.title_EN

src/rent_hotel/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.http import BadHeaderError
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.translation import ugettext_lazy as _
from django.contrib import messages
from tours.models import Category
from helpers.models import Helpers
from .models import Hotel


def get_lang(request):
    lang = request.LANGUAGE_CODE
    return lang


def get_company():
    return Helpers.objects.get(id=1).company_name


def rent_hotel_list(request):
    breadcrumbs = [
        {'url': '/', 'name': _('Home')},
        {'url': '#', 'name': _('Hotels in Lisbon'), 'active': True}
    ]
    footer = {
        'pt': Helpers.objects.get(id=1).about_footer_PT,
        'en': Helpers.objects.get(id=1).about_footer_EN,
        'de': Helpers.objects.get(id=1).about_footer_DE
    }
    queryset_list = Hotel.objects.all()
    lang = get_lang(request)
    query = request.GET.get('q')
    if query:
        if 'pt' in lang:
            queryset_list = queryset_list.filter(
                Q(title_PT__icontains=query) |
                Q(description_PT__icontains=query)
            ).distinct()
        else:
            if 'en' in lang:
                queryset_list = queryset_list.filter(
                    Q(title_EN__icontains=query) |
                    Q(description_EN__icontains=query)
                ).distinct()
            else:
                if 'de' in lang:
                    queryset_list = queryset_list.filter(
                        Q(title_DE__icontains=query) |
                        Q(description_DE__icontains=query))

    paginator = Paginator(queryset_list, 6)
    page_request_var = 'page'
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)

    context = {
        'footer': {
            'about': footer[lang],
            'icon': Helpers.objects.get(id=1).footer_icon
        },
        'categories_list': Category.objects.all(),
        'company': get_company(),
        'title': _('Hotels in Lisbon'),
        'object_list': queryset,
        'breadcrumbs': breadcrumbs,
        'page_request_var': page_request_var,
        'value': _('Add'),
    }

    return render(request, 'partials/rent-hotel.html', context)

src/templates/templates/_alerts.html
{% block messages %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }}">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <span>{{ message|safe }}</span>
</div>
{% endfor %}
{% endif %}
{% endblock %}

src/templates/templates/_contact_details.html
{% extends 'base.html' %}
{% load i18n %}
{% block description %}{{ object.description_SEO }}{% endblock description %}
{% block keywords %}{{ object.keywords_SEO }}{% endblock keywords %}
{% block content %}
    {% load staticfiles %}
    {% include 'templates/_breadcrumbs.html' %}
    <section class="details">
        <div class="container">
            <h4 class="display-4">{{ title }}</h4>
            <div class="row">
                <div class="col-md-6">
                    {% if object.img %}
                        <img style="max-height: 500px;   object-fit: cover;" class="img-fluid" src="{% static '/media/' %}{{ object.img }}" alt="" width="100%">
                    {% else %}
                        <p style="text-align: center"><small><em>{% trans 'place for image' %}</em></small></p>
                    {% endif %}
                    <small><em>SHORT BIO:</em></small>
                    <p class="card-text text-justify"> {{ object.short_bio}}</p>
                </div>
                <div class="col-md-6">
                <small><em>CATEGORY:</em></small>
                <p class="card-text"> {{ object.category}}</p>

                <small><em>CALL ME:</em></small>
            {% if object.mobile  %}
                <p class="card-text"><span class="fa fa-mobile"></span> {{ object.mobile }}</p>
            {% endif %}


            {% if object.email  %}
                <p class="card-text"><span class="fa fa-mail-forward"></span> {{ object.email }}</p>
            {% endif %}


            {% if object.whatsapp  %}
                <p class="card-text"><span class="fa fa-whatsapp"></span> {{ object.whatsapp }}</p>
            {% endif %}


            {% if object.viber  %}
                <p class="card-text"><span>viber:</span> {{ object.viber }}</p>
            {% endif %}


            {% if object.telegram  %}
                <p class="card-text"><span>telegram: </span>{{ object.telegram }}</p>
            {% endif %}


            {% if object.skype  %}
                <p class="card-text"><span class="fa fa-skype"></span> {{ object.skype }}</p>
            {% endif %}

                <small><em>SOCIAL NETWORKS:</em></small>


            {% if object.facebook  %}
                <p><a class="card-link" href="{{ object.facebook }}">{% trans 'Follow on ' %} Facebook <span class="fa fa-facebook"></span></a></p>
            {% endif %}


            {% if object.twitter  %}
                <p><a class="card-link" href="{{ object.twitter }}">{% trans 'Follow on ' %} Twitter <span class="fa fa-twitter"></span></a></p>
            {% endif %}


            {% if object.pinterest  %}
                <p><a class="card-link" href="{{ object.pinterest }}">{% trans 'Follow on ' %} Pinterest <span class="fa fa-pinterest"></span></a></p>
            {% endif %}


            {% if object.instagram  %}
                <p><a class="card-link" href="{{ object.instagram }}">{% trans 'Follow on ' %} Instagram <span class="fa fa-instagram"></span></a></p>
            {% endif %}


            {% if object.google  %}
                <p><a class="card-link" href="{{ object.google }}">{% trans 'Follow on ' %} Google + <span class="fa fa-google-plus"></span></a></p>
        {% endif %}
            {% if user.is_staff or user.is_superuser %}
                <a class="btn btn-sm btn-danger-outline" href="/contacts/{{ object.id }}/delete/">
                    <i class="fa fa-trash"></i> Delete</a>
                <a class="btn btn-sm btn-danger-outline" href="/contacts/{{ object.id }}/edit/">
                    <i class="fa fa-pencil-square-o"></i> Edit</a>
            {% endif %}
                    {% include 'templates/_share.html' %}

                </div>
            </div>
        </div>
    </section>
{% endblock %}

src/templates/templates/_contact_us_form.html
<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
    {{ contact_me.as_p }}
    <input type='submit' class='btn btn-lg btn-primary' value='{{ value }}' />
</form>

src/templates/templates/_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <nav>
        {% include 'templates/_breadcrumbs.html' %}
    </nav>
    <section>
    <div class="container">
        <h4 class="display-4">{{ title }}</h4>
{#        <div text-angular ng-model="htmlVariable"></div>#}
        <form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
            {{ form.as_p }}
            <input type='submit' class='btn btn-lg btn-primary' value='{{ value }}' />
        </form>
    </div>
    </section>
    <script>
    _.map(['textarea', 'input', 'label', 'select'], function(el){
                el === 'label' && $(el).attr('type') !== 'submit' ? $(el).addClass('my-label') : $(el).addClass('form-control');
            });
        $('select').css('height', '40px')
    </script>
{% endblock %}

src/templates/templates/_gallery_details.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    {% load staticfiles %}
    {% include 'templates/_breadcrumbs.html' %}
    <section class="details">
        <div class="container">
            <h4 class="display-4">{{ title }}</h4>
            {% include 'templates/_carousel.html' %}
            <small><em class="text-uppercase">{% trans 'title' %}</em></small>
            <h4 class="card-title">{{ object.title|upper }}</h4>
            <small><em class="text-uppercase">{% trans 'description' %}</em></small>
            <p class="card-text text-justify">{{ object.description }}</p>
            {% if user.is_staff or user.is_superuser %}
                <a class="btn btn-sm btn-danger-outline" href="/gallery/{{ object.id }}/delete/">
                    <i class="fa fa-trash"></i> Delete</a>
                <a class="btn btn-sm btn-danger-outline" href="/gallery/{{ object.id }}/edit/">
                    <i class="fa fa-pencil-square-o"></i> Edit
                </a>
            {% endif %}
            {% include 'templates/_share.html' %}
        </div>
    </section>
{% endblock %}

src/templates/templates/_modal_form.html
{% load i18n %}
{% load crispy_forms_tags %}
    <div class="container">
        <form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
            {{ form }}
            <input style="margin-top: 50px" type="submit" class="btn btn-lg btn-primary" value='{{ value }}' />
        </form>
    </div>
    <script>
        $('textarea').each(function(){
            $(this).addClass('form-control')
        })
        $('input').each(function(){
            $(this).addClass('form-control')
        })
        $('label').each(function(){
            $(this).addClass('my-label')
        })
    </script>

src/templates/templates/_news_details.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% load thumbnail %}
{% block content %}
    {% include 'templates/_breadcrumbs.html' %}
    <section class="details">
{#    <div class="side-image">#}
{#        <div class="images-wrapper"></div>#}
{#        <div class="side-image-content">#}
{#            <h4>Topic Name</h4>#}
{#            <h1>Message with a gradient image</h1>#}
{#            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam assumenda nihil suscipit obcaecati sit, cum quod corporis adipisci ipsam, fugiat, quae error. Eaque commodi, dicta quidem explicabo mollitia inventore quibusdam.#}
{#                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam assumenda nihil suscipit obcaecati sit, cum quod corporis adipisci ipsam, fugiat, quae error. Eaque commodi, dicta quidem explicabo mollitia inventore quibusdam.</p>#}
{#        </div>#}
{#    </div>#}
{##}
{##}



        <div class="container">
            <h1 class="display-4">{{ title }}</h1>
            <div class="row">
                <div class="row">
                <div class="col-md-6">
                    <div class="card-block">
                        {% if object.img %}
                            <img style="max-height: 500px;   object-fit: cover;" class="img-fluid" src="{% thumbnail object.img 720x480 crop="smart" %}" alt="" width="100%">
                        {% else %}
                            <p style="text-align: center"><small><em>{% trans 'place for image' %}</em></small></p>
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-6">
                    <h4 class="card-title">{{ object.title|upper }}</h4>
                    <p class="card-text text-justify">{{ object.description }}</p>
                    {% include 'templates/_share.html' %}
                    {% if user.is_staff or user.is_superuser %}
                        <a class="btn btn-sm btn-danger-outline" href="{% url 'news:list' %}{{ object.id }}/delete/">
                            <i class="fa fa-trash"></i> {% trans 'Delete' %}</a>
                        <a class="btn btn-sm btn-danger-outline" href="{% url 'news:list' %}{{ object.id }}/edit/">
                            <i class="fa fa-pencil-square-o"></i> {% trans 'Edit' %}</a>
                    {% endif %}
                </div>
                </div>
            </div>
            {% if user.is_staff or user.is_superuser %}
                <a class="btn btn-warning" href="{% url 'tour:create' %}">
                    <i class="fa fa-plus"></i> {% trans 'Create News' %}</a>
            {% endif %}
        </div>
    </section>
{% endblock %}

src/templates/templates/_offer_card.html
{% load static %}
{% load thumbnail %}
{% load i18n %}
<div class="card awesome-background">
    <div class="card-block">
        {% if 'pt' in request.LANGUAGE_CODE %}
            <h4 style="margin-top: 20px" class="card-title text-md-center">{{ object.title_PT }}</h4>
        {% endif %}
        {% if 'en' in request.LANGUAGE_CODE %}
            <h4 style="margin-top: 20px" class="card-title text-md-center">{{ object.title_EN }}</h4>
        {% endif %}
        {% if 'de' in request.LANGUAGE_CODE %}
            <h4 style="margin-top: 20px" class="card-title text-md-center">{{ object.title_DE }}</h4>
        {% endif %}
    </div>
    {% if object.img %}
        <a  href="{% if 'offer' in request.path %}{{ request.path }}{{ object.id }}{% else %}{% url 'offer:list' %}{{ object.id }}{% endif %}">
            <img width="100%" src="{% thumbnail object.img 720x480 crop="smart" %}" alt="{{ object.title }}" style="object-fit: cover;"></a>
    {% else %}
        <p style="text-align: center"><small><em>{% trans 'place for image' %}</em></small></p>
    {% endif %}
    <div class="card-block">
        {% if 'pt' in request.LANGUAGE_CODE %}
            <p class="card-text text-md-center">{{ object.description_PT|truncatechars:200 }}</p>
            <p class="text-md-center">
                <a class="btn btn-danger" href="{% url 'tour:list' %}{{ object.category.url }}">{% trans 'VER TODAS OFERTAS' %}</a>
            </p>
        {% endif %}
        {% if 'en' in request.LANGUAGE_CODE %}
            <p class="card-text text-md-center">{{ object.description_EN|truncatechars:200 }}</p>
            <p class="text-md-center">
                <a class="btn btn-danger" href="{% url 'tour:list' %}{{ object.category.url }}">{% trans 'SEE ALL OFFERS' %}</a>
            </p>
        {% endif %}
        {% if 'de' in request.LANGUAGE_CODE %}
            <p class="card-text text-md-center">{{ object.description_DE|truncatechars:200 }}</p>
            <p class="text-md-center">
                <a class="btn btn-danger" href="{% url 'tour:list' %}{{ object.category.url }}">{% trans 'SEHEN ALLE ANGEBOTE' %}</a>
            </p>
        {% endif %}
        {% if 'offer' in request.path %}
            {% include 'templates/_CRUD.html' %}
        {% else %}
            <p class="text-md-center"><a class="btn btn-danger-outline" href="{% url 'offer:list' %}{{ object.id }}" role="button">{% trans 'View details' %} &raquo;</a></p>
            {% if user.is_staff or user.is_superuser %}
                <p class="text-md-center">
                    <a class="btn btn-sm btn-danger-outline" href="{% url 'offer:list' %}{{ object.id }}/delete/">
                        <i class="fa fa-trash"></i> {% trans 'Delete' %}</a>
                    <a class="btn btn-sm btn-danger-outline" href="{% url 'offer:list' %}{{ object.id }}/edit/">
                        <i class="fa fa-pencil-square-o"></i> {% trans 'Edit' %}</a>
                </p>
            {% endif %}
        {% endif %}
    </div>
</div>

src/templates/templates/_related_links_details.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{{ title }}{% endblock title %}
{% block beadcrumbs %}
    {% include 'templates/_breadcrumbs.html' %}
{% endblock %}
{% block content %}
    <section>
        <div class="container">
            <h1 class="display-3">{{ title }}</h1>
        </div>
        <div class="container">
            <div class="row">

                {{ object.titlle }}

            </div>
            {% if user.is_staff or user.is_superuser %}
                <a class="btn btn-warning" href="{% url 'news:create' %}"><i class="fa fa-plus"></i> {% trans 'Create Article' %}</a>
            {% endif %}
        </div>
    </section>
{% endblock %}

src/templates/templates/_tour_card_de.html
{% load thumbnail %}
{% load i18n %}
<div class="card">
{% load i18n %}
    {% if object.img %}
        <a href="{% url 'tour:list' %}{{ object.id }}"><img style="height: 350px;width: 100%; object-fit: cover;" class="img-fluid" src="{% thumbnail object.img 720x480 crop="smart" %}" alt="{{ object.title_DE }}"></a>
    {% else %}
        {% if object.url  %}
            <a href="{% url 'tour:list' %}{{ object.id }}"><img style="height: 350px;width: 100%;   object-fit: cover;" class="img-fluid" src="{{ object.url }}" alt="{{ object.title_DE }}"></a>
        {% else %}
            <p style="text-align: center"><small><em>{% trans 'place for image' %}</em></small></p>
        {% endif %}
    {% endif %}
    <div class="card-block">
        <h4 class="card-title">{{ object.title_DE|upper }}
            {% if object.price %}
                | {{ object.price }} €
            {% endif %}</h4>
        <p class="card-text text-justify">{% autoescape off %}{{ object.description_DE|truncatechars:200}}{% endautoescape %}</p>
        <p>{{ object.created_on }}</p>
        <p><small><em class="text-uppercase">{% trans 'category' %}: </em><em><a href="/tours/{{ object.category.url }}">{{ object.category }}</a></em></small></p>
        <a href="{{ object.id }}" class="btn btn-danger text-uppercase" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">{% trans 'book now' %}</a>
        <a class="btn btn-danger-outline" href="/tours/{{ object.id }}" role="button">{% trans 'View details' %} &raquo;</a>
    </div>
    <div class="card-footer">
        {% include 'templates/_share.html' %}
        {% if user.is_staff %}
             <a class="btn btn-sm btn-danger-outline" href="{% url 'tour:list' %}{{ object.id }}/edit/">
                    <i class="fa fa-pencil-square-o"></i> {% trans 'Edit' %}</a>
            <a type="button" class="btn btn-sm btn-danger-outline" onclick="delete_contact({{ object.id }})" data-toggle="modal" data-target=".delete_tour"><i class="fa fa-trash"></i> {% trans 'Delete'%}</a></a>
        {% endif %}
    </div>
    {% include 'templates/modal/_delete_tour.html' %}
    {% include 'templates/_modal_book_now.html' %}
</div>

src/templates/templates/_tour_card_gb.html
{% load thumbnail %}
{% load i18n %}
<div class="card">
    {% if object.img %}
        <a href="/tours/{{ object.id }}"><img style="height: 350px;width: 100%; object-fit: cover;" class="img-fluid" src="{% thumbnail object.img 720x480 crop="smart" %}" alt="{{ object.title_EN }}"></a>
    {% else %}
        {% if object.url  %}
            <a href="/tours/{{ object.id }}"><img style="height: 350px;width: 100%;   object-fit: cover;" class="img-fluid" src="{{ object.url }}" alt="{{ object.title_EN }}"></a>
        {% else %}
            <p style="text-align: center"><small><em>{% trans 'place for image' %}</em></small></p>
        {% endif %}
    {% endif %}
    <div class="card-block">
        <h4 class="card-title">{{ object.title_EN|upper }}
            {% if object.price %}
                | {{ object.price }} €
            {% endif %}</h4>
        <p class="card-text text-justify">{% autoescape off %}{{ object.description_EN|truncatechars:200}}{% endautoescape %}</p>
        <p>{{ object.created_on }}</p>
        <p><small><em class="text-uppercase">{% trans 'category' %}: </em><em><a href="/tours/{{ object.category.url }}">{{ object.category }}</a></em></small></p>
        <a href="{{ object.id }}" class="btn btn-danger text-uppercase" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">{% trans 'book now' %}</a>
        <a class="btn btn-danger-outline" href="/tours/{{ object.id }}" role="button">{% trans 'View details' %} &raquo;</a>
    </div>
    <div class="card-footer">
        {% include 'templates/_share.html' %}
        {% if user.is_staff %}
             <a class="btn btn-sm btn-danger-outline" href="{% url 'tour:list' %}{{ object.id }}/edit/">
                    <i class="fa fa-pencil-square-o"></i> {% trans 'Edit' %}</a>
            <a type="button" class="btn btn-sm btn-danger-outline" onclick="delete_contact({{ object.id }})" data-toggle="modal" data-target=".delete_tour"><i class="fa fa-trash"></i> {% trans 'Delete'%}</a></a>
        {% endif %}
    </div>
    {% include 'templates/modal/_delete_tour.html' %}
    {% include 'templates/_modal_book_now.html' %}
</div>

src/templates/templates/_tour_card_pt.html
{% load thumbnail %}
{% load i18n %}
<div class="card">
    {% if object.img %}
        <a href="{% url 'tour:list' %}{{ object.id }}"><img style="height: 350px;width: 100%; object-fit: cover;" class="img-fluid" src="{% thumbnail object.img 720x480 crop="smart" %}" alt="{{ object.title_PT }}"></a>
    {% else %}
        {% if object.url  %}
            <a href="{% url 'tour:list' %}{{ object.id }}"><img style="height: 350px;width: 100%;   object-fit: cover;" class="img-fluid" src="{{ object.url }}" alt="{{ object.title_PT }}"></a>
        {% else %}
            <p style="text-align: center"><small><em>{% trans 'place for image' %}</em></small></p>
        {% endif %}
    {% endif %}
    <div class="card-block">
        <h4 class="card-title">{{ object.title_PT|upper }}
            {% if object.price %}
                | {{ object.price }} €
            {% endif %}</h4>
        <p class="card-text text-justify">{% autoescape off %}{{ object.description_PT|truncatechars:200}}{% endautoescape %}</p>
        <p>{{ object.created_on }}</p>
        <p><small><em class="text-uppercase">{% trans 'category' %}: </em><em><a href="/tours/{{ object.category.url }}">{{ object.category }}</a></em></small></p>
        <a class="btn btn-danger text-uppercase" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">{% trans 'book now' %}</a>
        <a class="btn btn-danger-outline" href="{% url 'tour:list' %}{{ object.id }}" role="button">{% trans 'View details' %} &raquo;</a>
    </div>
    <div class="card-footer">
        {% include 'templates/_share.html' %}
        {% if user.is_staff %}
             <a class="btn btn-sm btn-danger-outline" href="{% url 'tour:list' %}{{ object.id }}/edit/">
                    <i class="fa fa-pencil-square-o"></i> {% trans 'Edit' %}</a>
            <a type="button" class="btn btn-sm btn-danger-outline" onclick="delete_contact({{ object.id }})" data-toggle="modal" data-target=".delete_tour"><i class="fa fa-trash"></i> {% trans 'Delete'%}</a></a>
        {% endif %}
    </div>
    {% include 'templates/modal/_delete_tour.html' %}
    {% include 'templates/_modal_book_now.html' %}
</div>